### PR TITLE
Add logic to prevent anonymous user checkout orders. Little refactoring

### PR DESCRIPTION
**Pull request by laricko**
Thank you for contributing to Salesman, before you continue make sure that:
- Tests still pass: `poetry run pytest`
- There are no lint errors: `poetry run pre-commit run --all-files`

### CODE REVIEW

**Comment by dinoperovic** [comment]
Hi @chvmq, thanks for the PR. I will take a closer look as soon as I have some time, possibly this weekend. Could you in the meantime make sure that the tests and linting rules still pass? Running a quick test against your branch makes it break for me.

**Comment by dinoperovic** [comment]
@chvmq sorry, the flake8 pre-commit action was not running properly as they moved the repo. I've updated it, you can do the checks now.

**Comment by laricko** [comment]
@dinoperovic how to start test?
I have pytest 7.2.1
when I start pytest I got this error
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=. --cov-report=html
  inifile: /home/lari/projects/django-salesman/pytest.ini
  rootdir: /home/lari/projects/django-salesman
```

seems like my pytest can't parse this line `pytest: error: unrecognized arguments: --cov=. --cov-report=htm`
when I comment that line my test running but I got another issue

```
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by dinoperovic** [comment]
@laricko to run the tests you should do:
```bash
poetry install -E tests
poetry run pytest
```
Also check for lint errors:
```bash
poetry run pre-commit run --all-files
```

**Comment by laricko** [comment]
@dinoperovic I think I am done with my pull request. How do you feel about that feature?

**Comment by dinoperovic** [comment]
Hey @laricko, thanks for the PR, I will take a closer look this weekend.

**Comment by dinoperovic** [comment]
Hey @laricko, I went over your changes and I like the feature. I did however do some updates:

- moved the validation from serializer to the view so it applies to `GET /checkout/` as well
- used 403 forbidden error code instead of 400
- updated your test to include GET version and added some comments
- updated view action mapping method naming to be consistent with the original action name.
I realise methods `pay` and `pay_create` are a bit strangely named, but I will look to update the endpoint entirely to `payment` and `payment_create` in the future.

- added back the `dict` evaluation in `get_basket_response`.
I remember adding this because of some strange edge-case where the `serializer.data` is returned as proxy `ReturnDict` and not a dictionary. Can't exactly remember when it happens, possibly when using `?basket` on other endpoints, but would like to avoid this possible regression.

- updated docs a bit, added contributors to credits :)

**Review by dinoperovic — APPROVED** [review]

**Pull request merged**
